pal_impedance_control_${ARM_SIDE_PREFIX}:
  ros__parameters:
    type: pal_impedance_control/ImpedanceController

    joint_state_names:
      - arm_${ARM_SIDE_PREFIX}_1_joint
      - arm_${ARM_SIDE_PREFIX}_2_joint
      - arm_${ARM_SIDE_PREFIX}_3_joint
      - arm_${ARM_SIDE_PREFIX}_4_joint
      - arm_${ARM_SIDE_PREFIX}_5_joint
      - arm_${ARM_SIDE_PREFIX}_6_joint
      - arm_${ARM_SIDE_PREFIX}_7_joint

    joint_command_names:
      - arm_${ARM_SIDE_PREFIX}_1_joint
      - arm_${ARM_SIDE_PREFIX}_2_joint
      - arm_${ARM_SIDE_PREFIX}_3_joint
      - arm_${ARM_SIDE_PREFIX}_4_joint
      - arm_${ARM_SIDE_PREFIX}_5_joint
      - arm_${ARM_SIDE_PREFIX}_6_joint
      - arm_${ARM_SIDE_PREFIX}_7_joint

    interface_name: effort
    
    root_joint_type: JointModelFreeFlyer

    gains:
      arm_right_1_joint:
        kp: 49.940
        kd: 3.179
      arm_right_2_joint:
        kp: 49.940
        kd: 3.179
      arm_right_3_joint:
        kp: 26.177
        kd: 1.666
      arm_right_4_joint:
        kp: 26.177
        kd: 1.666
      arm_right_5_joint:
        kp: 26.177
        kd: 1.666
      arm_right_6_joint:
        kp: 26.177
        kd: 1.666
      arm_right_7_joint:
        kp: 26.177
        kd: 1.666
      arm_left_1_joint:
        kp: 49.940
        kd: 3.179
      arm_left_2_joint:
        kp: 49.940
        kd: 3.179
      arm_left_3_joint:
        kp: 26.177
        kd: 1.666
      arm_left_4_joint:
        kp: 26.177
        kd: 1.666
      arm_left_5_joint:   
        kp: 26.177
        kd: 1.666
      arm_left_6_joint:
        kp: 26.177
        kd: 1.666
      arm_left_7_joint:
        kp: 26.177
        kd: 1.666
      # arm_right_1_joint:
      #   kp: 50.0
      #   kd: 1.0
      # arm_right_2_joint:
      #   kp: 45.0
      #   kd: 0.5
      # arm_right_3_joint:
      #   kp: 70.0
      #   kd: 1.0
      # arm_right_4_joint:
      #   kp: 35.0
      #   kd: 0.0
      # arm_right_5_joint:
      #   kp: 15.0
      #   kd: 0.0
      # arm_right_6_joint:
      #   kp: 15.0
      #   kd: 0.0
      # arm_right_7_joint:
      #   kp: 10.0
      #   kd: 0.0
      # arm_left_1_joint:
      #   kp: 50.0
      #   kd: 1.0
      # arm_left_2_joint:
      #   kp: 45.0     
      #   kd: 0.5
      # arm_left_3_joint:
      #   kp: 70.0
      #   kd: 1.0
      # arm_left_4_joint:
      #   kp: 35.0
      #   kd: 0.0
      # arm_left_5_joint:   
      #   kp: 15.0
      #   kd: 0.0
      # arm_left_6_joint:
      #   kp: 15.0
      #   kd: 0.0
      # arm_left_7_joint:
      #   kp: 10.0
      #   kd: 0.0 
    





      
