pal_impedance_control_${ARM_SIDE_PREFIX}:
  ros__parameters:
    type: pal_impedance_control/ImpedanceController

    joint_state_names:
      - arm_${ARM_SIDE_PREFIX}_1_joint
      - arm_${ARM_SIDE_PREFIX}_2_joint
      - arm_${ARM_SIDE_PREFIX}_3_joint
      - arm_${ARM_SIDE_PREFIX}_4_joint
      - arm_${ARM_SIDE_PREFIX}_5_joint
      - arm_${ARM_SIDE_PREFIX}_6_joint
      - arm_${ARM_SIDE_PREFIX}_7_joint

    joint_command_names:
      - arm_${ARM_SIDE_PREFIX}_1_joint
      - arm_${ARM_SIDE_PREFIX}_2_joint
      - arm_${ARM_SIDE_PREFIX}_3_joint
      - arm_${ARM_SIDE_PREFIX}_4_joint
      - arm_${ARM_SIDE_PREFIX}_5_joint
      - arm_${ARM_SIDE_PREFIX}_6_joint
      - arm_${ARM_SIDE_PREFIX}_7_joint

    interface_name: effort
    root_joint_type: JointModelFreeFlyer

    gains:
      arm_right_1_joint: {kp: 50.0, kd: 1.0}
      arm_right_2_joint: {kp: 45.0, kd: 0.5}
      arm_right_3_joint: {kp: 70.0, kd: 1.0}
      arm_right_4_joint: {kp: 35.0, kd: 0.0}
      arm_right_5_joint: {kp: 15.0, kd: 0.0}
      arm_right_6_joint: {kp: 15.0, kd: 0.0}
      arm_right_7_joint: {kp: 10.0, kd: 0.0}
      arm_left_1_joint: {kp: 50.0, kd: 1.0}
      arm_left_2_joint: {kp: 45.0, kd: 0.5}
      arm_left_3_joint: {kp: 70.0, kd: 1.0}
      arm_left_4_joint: {kp: 35.0, kd: 0.0}
      arm_left_5_joint: {kp: 15.0, kd: 0.0}
      arm_left_6_joint: {kp: 15.0, kd: 0.0}
      arm_left_7_joint: {kp: 10.0, kd: 0.0}

  
arm_${ARM_SIDE_PREFIX}_pos_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController

    joints:
      - arm_${ARM_SIDE_PREFIX}_1_joint
      - arm_${ARM_SIDE_PREFIX}_2_joint
      - arm_${ARM_SIDE_PREFIX}_3_joint
      - arm_${ARM_SIDE_PREFIX}_4_joint
      - arm_${ARM_SIDE_PREFIX}_5_joint
      - arm_${ARM_SIDE_PREFIX}_6_joint
      - arm_${ARM_SIDE_PREFIX}_7_joint

    command_joints:
      - pal_impedance_control_${ARM_SIDE_PREFIX}/arm_${ARM_SIDE_PREFIX}_1_joint
      - pal_impedance_control_${ARM_SIDE_PREFIX}/arm_${ARM_SIDE_PREFIX}_2_joint
      - pal_impedance_control_${ARM_SIDE_PREFIX}/arm_${ARM_SIDE_PREFIX}_3_joint
      - pal_impedance_control_${ARM_SIDE_PREFIX}/arm_${ARM_SIDE_PREFIX}_4_joint
      - pal_impedance_control_${ARM_SIDE_PREFIX}/arm_${ARM_SIDE_PREFIX}_5_joint
      - pal_impedance_control_${ARM_SIDE_PREFIX}/arm_${ARM_SIDE_PREFIX}_6_joint
      - pal_impedance_control_${ARM_SIDE_PREFIX}/arm_${ARM_SIDE_PREFIX}_7_joint

    command_interfaces: [position]
    state_interfaces: [position]



